<link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $this->getMainFont()); ?>' rel='stylesheet' type='text/css'>
<style type="text/css">
.wdph-megamenu-container .wdph-megamenu-navigation-container { font-family: <?php echo $this->getMainFont(); ?>; }
.wdph-megamenu-container ul.wdph-megamenu { background-color: <?php echo $this->megamenuHelper->getConfig('appearance/background_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container a, .wdph-megamenu-container .wdph-megamenu-navigation-container a:visited { color: <?php echo $this->megamenuHelper->getConfig('appearance/font_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.level-0 { font-size: <?php echo $this->megamenuHelper->getConfig('appearance/level0_font_size'); ?>; font-weight: <?php echo $this->megamenuHelper->getConfig('appearance/level0_font_weight'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.visible>a { color: <?php echo $this->megamenuHelper->getConfig('appearance/font_hover_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.level-0:hover { background-color: <?php echo $this->megamenuHelper->getConfig('appearance/item_hover_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-submenu { background-color: <?php echo $this->megamenuHelper->getConfig('appearance/dropdown_background_color'); ?>; }
</style>