<?php
$gFont = $this->getMainFont();
if($gFont != 'NONE'): ?>
<link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $gFont); ?>' rel='stylesheet' type='text/css'>
<?php endif; ?>
<style type="text/css">
<?php if($gFont != 'NONE'): ?>
.wdph-megamenu-container .wdph-megamenu-navigation-container { font-family: <?php echo $gFont; ?>; }
<?php endif; ?>
.wdph-megamenu-container ul.wdph-megamenu { background-color: <?php echo $this->megamenuHelper->getConfig('appearance/background_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li { color: <?php echo $this->megamenuHelper->getConfig('appearance/font_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.level-0.home { color: <?php echo $this->megamenuHelper->getConfig('appearance/home_item_font_color'); ?>; background-color: <?php echo $this->megamenuHelper->getConfig('appearance/home_item_back_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.visible.level-0.home { color: <?php echo $this->megamenuHelper->getConfig('appearance/home_item_font_hover_color'); ?>; background-color: <?php echo $this->megamenuHelper->getConfig('appearance/home_item_back_hover_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.visible { color: <?php echo $this->megamenuHelper->getConfig('appearance/font_hover_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.level-0 { font-size: <?php echo $this->megamenuHelper->getConfig('appearance/level0_font_size'); ?>; font-weight: <?php echo $this->megamenuHelper->getConfig('appearance/level0_font_weight'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.level-0.wdph-dropdown-type-fullwidth li { font-size: <?php echo $this->megamenuHelper->getConfig('appearance/fullwidth_level2_font_size'); ?> ; font-weight: <?php echo $this->megamenuHelper->getConfig('appearance/fullwidth_level2_font_weight'); ?>; color: <?php echo $this->megamenuHelper->getConfig('appearance/fullwidth_level2_font_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.level-0.wdph-dropdown-type-fullwidth li.visible { color: <?php echo $this->megamenuHelper->getConfig('appearance/fullwidth_level2_font_hover_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.level-0.wdph-dropdown-type-fullwidth li.level-1 { font-size: <?php echo $this->megamenuHelper->getConfig('appearance/fullwidth_level1_font_size'); ?> ; font-weight: <?php echo $this->megamenuHelper->getConfig('appearance/fullwidth_level1_font_weight'); ?>; color: <?php echo $this->megamenuHelper->getConfig('appearance/fullwidth_level1_font_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.level-0.wdph-dropdown-type-fullwidth li.level-1.visible { color: <?php echo $this->megamenuHelper->getConfig('appearance/fullwidth_level1_font_hover_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container li.level-0.visible { background-color: <?php echo $this->megamenuHelper->getConfig('appearance/item_hover_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-submenu { background-color: <?php echo $this->megamenuHelper->getConfig('appearance/dropdown_background_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container .wdph-megamenu-item.wdph-dropdown-type-classic li { font-size: <?php echo $this->megamenuHelper->getConfig('appearance/classic_items_font_size'); ?>; font-weight: <?php echo $this->megamenuHelper->getConfig('appearance/classic_items_font_weight'); ?>; color: <?php echo $this->megamenuHelper->getConfig('appearance/classic_items_font_color'); ?>; }
.wdph-megamenu-container .wdph-megamenu-navigation-container .wdph-megamenu-item.wdph-dropdown-type-classic li.visible { color: <?php echo $this->megamenuHelper->getConfig('appearance/classic_items_font_hover_color'); ?>;}
.wdph-megamenu-container .wdph-megamenu-navigation-container li .wdph-megamenu-item-add-label.label1 { color: <?php echo $this->megamenuHelper->getConfig('appearance/label1_font_color'); ?>; background-color: <?php echo $this->megamenuHelper->getConfig('appearance/label1_background_color'); ?>;}
.wdph-megamenu-container .wdph-megamenu-navigation-container li .wdph-megamenu-item-add-label.label2 { color: <?php echo $this->megamenuHelper->getConfig('appearance/label2_font_color'); ?>; background-color: <?php echo $this->megamenuHelper->getConfig('appearance/label2_background_color'); ?>;}
.wdph-megamenu-container .wdph-megamenu-navigation-container li .wdph-megamenu-item-add-label.label3 { color: <?php echo $this->megamenuHelper->getConfig('appearance/label3_font_color'); ?>; background-color: <?php echo $this->megamenuHelper->getConfig('appearance/label3_background_color'); ?>;}
</style>